version: '3'
services:
  postgres:
    container_name: rls-postgres
    build: ./postgres
    ports:
      - 15432:5432
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=rls
  api:
    container_name: rls-api
    build: ./api
    volumes:
      - ./api:/go/api
    ports:
      - 18888:8080
    links:
      - postgres
